version: '3'

services:
  web:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - 8080:80
    networks:
      - internal

networks:
  internal:
    driver: bridge
